### ISSUE TITLE
miss use of printf 

### ISSUE THREAD

**Issue by bokunodev** [InsaneMiner/EpicFS#1]
https://github.com/InsaneMiner/EpicFS/blob/abe58bd3e6fa1fbf5fd4c7cddd9a12cdf08fb8f1/fs.c#L158
https://github.com/InsaneMiner/EpicFS/blob/abe58bd3e6fa1fbf5fd4c7cddd9a12cdf08fb8f1/fs.c#L159

**Comment by InsaneMiner** [comment]
What should it be?

**Comment by bokunodev** [comment]
https://github.com/InsaneMiner/EpicFS/blob/abe58bd3e6fa1fbf5fd4c7cddd9a12cdf08fb8f1/fs.h#L1
consider using header guard instead.

https://github.com/InsaneMiner/EpicFS/blob/abe58bd3e6fa1fbf5fd4c7cddd9a12cdf08fb8f1/fs.c#L127
`fwrite` is a function. it'll never equal to `NULL`
to check file error, use `ferror(FILE* file)` instead.

**Comment by InsaneMiner** [comment]
Why should I use header guards, pragma works.

**Comment by bokunodev** [comment]
ok, btw what `find` function do? what the use `BLOCK` ??

**Comment by InsaneMiner** [comment]
> ok, btw what `find` function do? what the use `BLOCK` ??

“find” finds a file by name, then returns it’s offset. Block is the block size of each block.

**Comment by bokunodev** [comment]
but `fileCreate` function does not use `block`? and both file content and file struct is not multiple of blocks.

**Comment by InsaneMiner** [comment]
> but `fileCreate` function does not use `block`? and both file content and file struct is not multiple of blocks.

It’s a work in process thing, I’m working on using blocks when writing. I’m going to have a block length and a file length

**Comment by bokunodev** [comment]
try to make a flowchart. it will make it easier to understand, how it works or how its suppose to works. also for consistency.

about the `#pragma once`. there is a reason, why it never made into C standard.
when you have multiple header with different name or path, it will include both even if the content is the same.
sure, it can be fixed using checksum instead of comparing file names (as proposed).
but, calculating the checksum will be come a new bottleneck. so that why it never accepted.

**Comment by bokunodev** [comment]
> > but `fileCreate` function does not use `block`? and both file content and file struct is not multiple of blocks.
> 
> It’s a work in process thing, I’m working on using blocks when writing. I’m going to have a block length and a file length

but `fileRead` function use it to calculate offset ?

**Comment by InsaneMiner** [comment]
> try to make a flowchart. it will make it easier to understand, how it works or how its suppose to works. also for consistency.
> 
> about the `#pragma once`. there is a reason, why it never made into C standard.
> when you have multiple header with different name or path, it will include both even if the content is the same.
> sure, it can be fixed using checksum instead of comparing file names (as proposed).
> but, calculating the checksum will be come a new bottleneck. so that why it never accepted.

Oh makes sense, I will change it.

**Comment by InsaneMiner** [comment]
> > It’s a work in process thing, I’m working on using blocks when writing. I’m going to have a block length and a file length
> 
> but `find` function use it to calculate offset ?

What do you mean?

**Comment by InsaneMiner** [comment]
Well this one does not, like I said I’m going to use blocks soon, for now it does not.

**Comment by InsaneMiner** [comment]
> https://github.com/InsaneMiner/EpicFS/blob/abe58bd3e6fa1fbf5fd4c7cddd9a12cdf08fb8f1/fs.c#L158
> 
> 
> https://github.com/InsaneMiner/EpicFS/blob/abe58bd3e6fa1fbf5fd4c7cddd9a12cdf08fb8f1/fs.c#L159

Fixed this, I’m closing the issue.
